gems:
- jekyll-assets
- bourbon
- neat

# Structure configuration
source: source
destination: build

# Permalinks
permalink: none

assets:
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "bundle.css"
  digest: true
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js


# Site settings
title: Best Rent Mallorca
description: the place to be

# Name of project on Github
baseurl: 

# Build settings
markdown: redcarpet

#Polyglot
languages: ["en", "es", "de","fr"] #"ru", "fr", "it"
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]

herotext:
  en: "Excursions, Bikes, Cars, Scooters, Nigh life, Water sports, Quads, Jetski!"
  es: "Excursiones, Bicicletas, Coches, Motos, Vida nocturna, Deportes acuáticos, Quads, Jet ski!"
  fr: "Excursions, Motos, Voitures, Scooters, Vie nocturne, Sports nautiques, Quads, Jetski!"
  de: "Ausflüge, Fahrräder, Autos, Motorroller , Nachtleben, Wassersport, Quads, Jetskis!"

contact_text: 
  en: "Contact Best Rent Mallorca"
  es: "Contact Best Rent Mallorca"
  de: "Contact Best Rent Mallorca"
  fr: "Contact Best Rent Mallorca"

