gems:
- jekyll-assets
- bourbon
- neat

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

# Site settings
title: David Martins
description: Prototyping starter kit for Jekyll

# Name of project on Github
baseurl: /

# Build settings
markdown: kramdown

languages: ["en",  "es"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]