gems:
- jekyll-assets
- bourbon
- neat

# Structure configuration
source: source
destination: build

# Permalinks
permalink: none

assets:
  cachebust: soft

# Site settings
title: David Martins
description: Prototyping starter kit for Jekyll

# Name of project on Github
baseurl: 

# Build settings
markdown: kramdown

#Polyglot
languages: ["en", "es", "de", "ru", "fr", "it"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]